# Generated by Django 4.2.20 on 2025-04-15 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SysAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('reward', models.IntegerField(default=1)),
                ('question_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing_models.question')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_time', models.TimeField()),
                ('text', models.CharField(max_length=200, null=True)),
                ('answer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing_models.sysanswers')),
                ('question_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing_models.question')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time_to_complete', models.TimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('wasted_time', models.TimeField(null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing_models.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='test_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing_models.test'),
        ),
    ]
