# Generated by Django 4.2.20 on 2025-07-22 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswers',
            name='answer_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testing_models.sysanswers'),
        ),
    ]
